### ISSUE TITLE
Question about the mode: "single" and "pairwise"

### ISSUE THREAD

**Issue by CicoZhang** [mana-ysh/knowledge-graph-embeddings#2]
I am wondering if you could give a simple explanation of the mode "single" and "pairwise". Is there any preference to stick to one mode? 

Thank you in advance.

**Comment by mana-ysh** [comment]
These two modes have the different objective functions.
“single” mode uses the negative log likelihood of sigmoid activation as an objective, and “pairwise” mode uses max-margin loss.

In my opinion, there isn’t the significant difference in performance between single and pairwise mode, but it may depend on the model or dataset you use.

**Comment by CicoZhang** [comment]
Great, thank you for the explanation!
