### ISSUE TITLE
Entity list and relation list

### ISSUE THREAD

**Issue by kaihuchen** [mana-ysh/knowledge-graph-embeddings#4]
It seems that two files needed by train.py and test.py (i.e., through the --ent and --rel arguments),  i.e. the **entity list** and the **relation list**, are not included in this repository.

Can I assume that:

- The relation list should contain the list of known relation names (18 of them in the WordNet samples, e.g., _member_of_domain_topic, _also_see, etc.)? 
- The entity list should contain the list of known entity IDs (e.g., 14854262, 00590383, etc.) which can be extracted from, say, wordnet-mlj12-train.txt?

It is easy enough for me to write my own code to generate these files, but I just want to make sure that the above are what's expected. Thanks!

**Comment by mana-ysh** [comment]
Hi @kaihuchen 

Your assumption is right. 
Entity/Relation list files contain each ID or names line by line and are generated from training triplet file. (If you run and trace `preprocess.sh`, it is more easy to understand, I think.)

**Comment by kaihuchen** [comment]
@mana-ysh 

Manabe San, much appreciated for the confirmation!
