### ISSUE TITLE
GPU implementation

### ISSUE THREAD

**Issue by JunhengH** [mana-ysh/knowledge-graph-embeddings#9]
Great work for all the popular KG embedding model! 

Are you still working on this project or considering to update another GPU-adaptable version?

**Comment by mana-ysh** [comment]
Hi @JunhengH 
Sorry for late reply.
I don’t any plan to support GPU.
But you may be able to use [cupy](https://github.com/cupy/cupy), which has the same interface as numpy, like this.
```python
import cupy as np
```
But I didn’t test it.
